[general]

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@postgres:5432/graph-node"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"
[chains.eos]
protocol = "substreams"
shard = "primary"
provider = [
    { label = "substreams-eos", details = { type = "substreams", url = "http://eos-sfsf69.mar.eosn.io:9000" } },
]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = ["default"]
